//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExeTest.wsMirth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.connectors.connect.mirth.com/", ConfigurationName="wsMirth.DefaultAcceptMessage")]
    public interface DefaultAcceptMessage {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento arg0 dallo spazio dei nomi  non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ExeTest.wsMirth.acceptMessageResponse acceptMessage(ExeTest.wsMirth.acceptMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ExeTest.wsMirth.acceptMessageResponse> acceptMessageAsync(ExeTest.wsMirth.acceptMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class acceptMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="acceptMessage", Namespace="http://ws.connectors.connect.mirth.com/", Order=0)]
        public ExeTest.wsMirth.acceptMessageRequestBody Body;
        
        public acceptMessageRequest() {
        }
        
        public acceptMessageRequest(ExeTest.wsMirth.acceptMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class acceptMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public acceptMessageRequestBody() {
        }
        
        public acceptMessageRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class acceptMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="acceptMessageResponse", Namespace="http://ws.connectors.connect.mirth.com/", Order=0)]
        public ExeTest.wsMirth.acceptMessageResponseBody Body;
        
        public acceptMessageResponse() {
        }
        
        public acceptMessageResponse(ExeTest.wsMirth.acceptMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class acceptMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public acceptMessageResponseBody() {
        }
        
        public acceptMessageResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DefaultAcceptMessageChannel : ExeTest.wsMirth.DefaultAcceptMessage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DefaultAcceptMessageClient : System.ServiceModel.ClientBase<ExeTest.wsMirth.DefaultAcceptMessage>, ExeTest.wsMirth.DefaultAcceptMessage {
        
        public DefaultAcceptMessageClient() {
        }
        
        public DefaultAcceptMessageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DefaultAcceptMessageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DefaultAcceptMessageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DefaultAcceptMessageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExeTest.wsMirth.acceptMessageResponse ExeTest.wsMirth.DefaultAcceptMessage.acceptMessage(ExeTest.wsMirth.acceptMessageRequest request) {
            return base.Channel.acceptMessage(request);
        }
        
        public string acceptMessage(string arg0) {
            ExeTest.wsMirth.acceptMessageRequest inValue = new ExeTest.wsMirth.acceptMessageRequest();
            inValue.Body = new ExeTest.wsMirth.acceptMessageRequestBody();
            inValue.Body.arg0 = arg0;
            ExeTest.wsMirth.acceptMessageResponse retVal = ((ExeTest.wsMirth.DefaultAcceptMessage)(this)).acceptMessage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExeTest.wsMirth.acceptMessageResponse> ExeTest.wsMirth.DefaultAcceptMessage.acceptMessageAsync(ExeTest.wsMirth.acceptMessageRequest request) {
            return base.Channel.acceptMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExeTest.wsMirth.acceptMessageResponse> acceptMessageAsync(string arg0) {
            ExeTest.wsMirth.acceptMessageRequest inValue = new ExeTest.wsMirth.acceptMessageRequest();
            inValue.Body = new ExeTest.wsMirth.acceptMessageRequestBody();
            inValue.Body.arg0 = arg0;
            return ((ExeTest.wsMirth.DefaultAcceptMessage)(this)).acceptMessageAsync(inValue);
        }
    }
}
