//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlt_ricradiologica
    {
        public long seriale { get; set; }
        public string objectid { get; set; }
        public System.DateTime data_creazione { get; set; }
        public Nullable<System.DateTime> data_modifica { get; set; }
        public string nomeutente_creazione { get; set; }
        public string nomeutente_modifica { get; set; }
        public string locker { get; set; }
        public string versione { get; set; }
        public string pdfcreato { get; set; }
        public string idepisodio { get; set; }
        public string esami { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string ora { get; set; }
        public string motivo { get; set; }
        public string statopaziente { get; set; }
        public Nullable<bool> urgente { get; set; }
        public Nullable<bool> dimprotetta { get; set; }
        public string quesitoclinico { get; set; }
        public string nomeesami { get; set; }
    }
}
