//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlt_TableListaCampi
    {
        public long seriale { get; set; }
        public string nome_campo { get; set; }
        public string label_campo { get; set; }
        public int lunghezza_campo { get; set; }
        public bool uniquevalue { get; set; }
        public bool obbligatorio { get; set; }
        public bool @readonly { get; set; }
        public bool visibile { get; set; }
        public string tipo_campo { get; set; }
        public int index_campo { get; set; }
        public string systemtype { get; set; }
        public string nome_tabella { get; set; }
        public string campi_controllati { get; set; }
        public Nullable<bool> controllato { get; set; }
        public string tipo_controllore { get; set; }
        public Nullable<bool> visibilepdf { get; set; }
    }
}
