//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlt_vcardmf
    {
        public long seriale { get; set; }
        public string objectid { get; set; }
        public System.DateTime data_creazione { get; set; }
        public Nullable<System.DateTime> data_modifica { get; set; }
        public string nomeutente_creazione { get; set; }
        public string nomeutente_modifica { get; set; }
        public string locker { get; set; }
        public string versione { get; set; }
        public string pdfcreato { get; set; }
        public int idservizioepisodio { get; set; }
        public string malattiecuorechi { get; set; }
        public string malattiecuorequali { get; set; }
        public string ipertensionechi { get; set; }
        public string ipertensionenote { get; set; }
        public string ictuschi { get; set; }
        public string ipercolesterolemiachi { get; set; }
        public string malattierenalichi { get; set; }
        public Nullable<bool> malattiecuore { get; set; }
        public Nullable<bool> ipertensione { get; set; }
        public Nullable<bool> ictus { get; set; }
        public Nullable<bool> ipercolesterolemia { get; set; }
        public Nullable<bool> malattierenali { get; set; }
        public string diabetechi { get; set; }
        public Nullable<bool> diabete { get; set; }
        public string asmachi { get; set; }
        public Nullable<bool> asma { get; set; }
        public string allergiechi { get; set; }
        public string malattiefegatochi { get; set; }
        public string altrochi { get; set; }
        public string morteimprovvisachi { get; set; }
        public string malattiegenetichechi { get; set; }
        public Nullable<bool> allergie { get; set; }
        public Nullable<bool> malattiefegato { get; set; }
        public Nullable<bool> morteimprovvisa { get; set; }
        public Nullable<bool> malattiegenetiche { get; set; }
        public string malattiegenetichenote { get; set; }
        public Nullable<bool> altro { get; set; }
        public string altroquali { get; set; }
        public Nullable<bool> varicella { get; set; }
        public Nullable<bool> rosolia { get; set; }
        public Nullable<bool> parotite { get; set; }
        public Nullable<bool> malattiareumatica { get; set; }
        public Nullable<bool> anemia { get; set; }
        public Nullable<bool> pertosse { get; set; }
        public Nullable<bool> morbillo { get; set; }
        public Nullable<bool> scarlattina { get; set; }
        public Nullable<bool> meningite { get; set; }
        public Nullable<bool> mononucleosi { get; set; }
        public Nullable<bool> scoliosi { get; set; }
        public Nullable<bool> polmoniti { get; set; }
        public string farmaciinterapia { get; set; }
        public string farmaciallergie { get; set; }
        public string pressionearteriosa { get; set; }
        public string frequenzacardiaca { get; set; }
        public string edeminote { get; set; }
        public Nullable<bool> edemi { get; set; }
        public string ingrossamentofegatonote { get; set; }
        public Nullable<bool> ingrossamentofegato { get; set; }
        public string allergiequali { get; set; }
    }
}
