//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlt_esameradio
    {
        public long esameidid { get; set; }
        public string esamedesc { get; set; }
        public int esametipo { get; set; }
        public string esamestato { get; set; }
        public Nullable<System.DateTime> esamedataprenotazione { get; set; }
        public Nullable<System.DateTime> esamedataesecuzione { get; set; }
        public string esamereferto { get; set; }
        public string esame_ext_key { get; set; }
        public string esamerichid { get; set; }
    }
}
