//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int IdMedia { get; set; }
        public string MimeType { get; set; }
        public byte[] MediaContent { get; set; }
        public int MediaLenght { get; set; }
        public int IdEpisodio { get; set; }
        public short LinkType { get; set; }
        public int LinkId { get; set; }
        public string OriginalName { get; set; }
        public System.DateTime DataInserimento { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string objectid { get; set; }
        public string usercreator { get; set; }
        public Nullable<bool> flag_remove { get; set; }
        public Nullable<System.DateTime> datarimozione { get; set; }
        public string userremove { get; set; }
    }
}
