//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Seriale { get; set; }
        public string Descrizione { get; set; }
        public string UrlContent { get; set; }
        public string UrlMenu { get; set; }
        public string UrlButton { get; set; }
        public string PathIcona { get; set; }
        public Nullable<decimal> Ordinamento { get; set; }
        public Nullable<int> IdPadre { get; set; }
        public string ColoreSelezionato { get; set; }
        public string ColoreDeselezionato { get; set; }
        public string onclickFunc { get; set; }
    }
}
